import type { Metadata } from "next";
import { Geist, Roboto } from "next/font/google";
import "../app/globals.css";
import Navbar from "./Navbar";
import AuthProvider from "./auth/Provider";
import GoogleAnalyticsScript from "./GoogleAnalyticsScript";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ['500', '700']
})

export const metadata: Metadata = {
  title: "Hussain First NextApp",
  description: "Generated by create next app following codewithmosh nextjs learning ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleAnalyticsScript />
      <body
        className={roboto.className}
      >
        <AuthProvider>

          <Navbar />
          <main className="p-5">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
